In [1]:
# Google Colab: https://colab.research.google.com/

In [2]:
import numpy as np # Numpy kütüphanesini yükle

In [3]:
np.__version__ # Numpy sürüm bilgisi

'1.23.4'

In [4]:
liste = [1,2,3,4,5,6]

In [5]:
print(liste)

[1, 2, 3, 4, 5, 6]


In [6]:
liste2 = [1,2,3,"elma",True, ["a","b"]]

In [7]:
print(liste2)

[1, 2, 3, 'elma', True, ['a', 'b']]


In [8]:
liste + 1 # ?

TypeError: can only concatenate list (not "int") to list

In [9]:
yeniListe = []
for rakam in liste:
    rakam = rakam + 1
    yeniListe.append(rakam)
print(yeniListe)

[2, 3, 4, 5, 6, 7]


In [10]:
# Numpy Array Oluştur
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [11]:
np.array([3.14, 2, 3, 5])

array([3.14, 2.  , 3.  , 5.  ])

In [12]:
np.array([1,2,3,4], dtype='float32') # dtype: Data Type

array([1., 2., 3., 4.], dtype=float32)

In [13]:
np.array([range(i, i+3) for i in [2,4,5]])

array([[2, 3, 4],
       [4, 5, 6],
       [5, 6, 7]])

In [15]:
print(range(2,5))

range(2, 5)


In [19]:
list(range(2,5)) # son eleman dahil değildir

[2, 3, 4]

In [20]:
# Sıfırlardan oluşan array
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
np.ones((4,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
np.full((4,3), 3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [62]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
np.linspace(0, 1, 5) # !

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
np.random.random() # uniform dağılım

0.05980160803286527

In [33]:
np.random.random((4, 4)) # uniform dağılım

array([[0.93189868, 0.95829187, 0.44895617, 0.3222515 ],
       [0.96994901, 0.72023819, 0.55256311, 0.50018994],
       [0.7745171 , 0.98531168, 0.69632319, 0.71041066],
       [0.56630108, 0.44116965, 0.20638386, 0.76408491]])

In [36]:
np.random.normal() # Normal dağılım - ortalaması 0, standart sapması 1 olan rasgele sayılar

2.478397936881219

In [37]:
np.random.randint(0, 10, (3, 3))

array([[3, 4, 5],
       [3, 4, 1],
       [3, 5, 9]])

In [61]:
np.random.randint(5)

3

In [63]:
arr1 = np.random.randint(10, size=6)

In [64]:
arr2 = np.random.randint(10, size=(3, 4))

In [65]:
arr3 = np.random.randint(10, size=(3,4,5))

In [66]:
print(arr3.ndim) # boyut sayısı

3


In [67]:
print(arr3.shape) # boyutların kaçar elemandan oluştukları

(3, 4, 5)


In [68]:
print(arr3.size) # array'in kaç tane elemandan oluştuğunu gösterir

60


In [69]:
print(arr3.dtype) # array elemanlarının data type'ı gösterir

int32


In [70]:
arr1

array([4, 1, 3, 2, 9, 4])

In [72]:
arr1[3] # sıfın indeksli 

2

In [73]:
arr1[-1] # array'in son elemanı

4

In [74]:
arr1[-2] # array'in sondan ikinci elemanı

9

In [75]:
arr2

array([[1, 6, 6, 5],
       [6, 4, 3, 7],
       [4, 9, 8, 9]])

In [76]:
arr2[1,2] # sıfır index!

3

In [77]:
arr2[2,3] # ?

9

In [78]:
arr1

array([4, 1, 3, 2, 9, 4])

In [79]:
arr1[2] = 3.14 # başarılı olur mu?

In [80]:
arr1

array([4, 1, 3, 2, 9, 4])

In [81]:
arr1[2] = 5.2

In [82]:
arr1

array([4, 1, 5, 2, 9, 4])

In [83]:
arr2

array([[1, 6, 6, 5],
       [6, 4, 3, 7],
       [4, 9, 8, 9]])

In [84]:
arr2[0,0:3] # arr[start:stop:step]

array([1, 6, 6])

In [85]:
arr1

array([4, 1, 5, 2, 9, 4])

In [86]:
arr1[2:4]

array([5, 2])

In [87]:
arr2[1:3,1:3]

array([[4, 3],
       [9, 8]])

In [88]:
arr2[1:3,1:4] # sub-array

array([[4, 3, 7],
       [9, 8, 9]])

In [89]:
arr2[:,0] # ilk kolon

array([1, 6, 4])

In [90]:
# Array'lerin kopyalarını oluştur
arr2_kopya = arr2.copy()

In [91]:
arr2_kopya

array([[1, 6, 6, 5],
       [6, 4, 3, 7],
       [4, 9, 8, 9]])

In [98]:
arr2_copy = arr2 # bir array'den başka bir array oluştur ! yeni array'de yapılacak değişiklikler ilk array'i de değiştirir !

In [93]:
arr2_copy

array([[1, 6, 6, 5],
       [6, 4, 3, 7],
       [4, 9, 8, 9]])

In [94]:
arr2

array([[1, 6, 6, 5],
       [6, 4, 3, 7],
       [4, 9, 8, 9]])

In [95]:
arr2_copy[0,:] = 0 # ilk satır değerlerini sıfır olarak değiştir

In [96]:
arr2_copy

array([[0, 0, 0, 0],
       [6, 4, 3, 7],
       [4, 9, 8, 9]])

In [97]:
arr2

array([[0, 0, 0, 0],
       [6, 4, 3, 7],
       [4, 9, 8, 9]])

In [99]:
arr2_kopya[1,:] = 0

In [100]:
arr2_kopya

array([[1, 6, 6, 5],
       [0, 0, 0, 0],
       [4, 9, 8, 9]])

In [101]:
arr2

array([[0, 0, 0, 0],
       [6, 4, 3, 7],
       [4, 9, 8, 9]])

In [102]:
grid = np.arange(1,10)

In [103]:
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
grid.reshape((3,3)) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
grid.reshape((4,4)) # Hata verir

ValueError: cannot reshape array of size 9 into shape (4,4)

In [109]:
grid.reshape((2,2)) # Hata verir!

ValueError: cannot reshape array of size 9 into shape (2,2)

In [111]:
x = np.array([1,2,3]) # tek boyutlu bir array

In [112]:
print(x)

[1 2 3]


In [113]:
x.reshape((1,3))

array([[1, 2, 3]])

In [114]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [115]:
# Array birleştirme
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [116]:
z = [7, 8, 9]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
np.concatenate(x,y,z) # Hata verir ! Doğru kullanım: np.concatenate([x,y,z])

TypeError: only integer scalar arrays can be converted to a scalar index

In [118]:
arr2

array([[0, 0, 0, 0],
       [6, 4, 3, 7],
       [4, 9, 8, 9]])

In [120]:
arr2b = np.eye(4)

In [121]:
arr2b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [122]:
np.concatenate([arr2, arr2b]) # arr2b, arr2'nin altında olacak şekilde yeni bir array oluşturur

array([[0., 0., 0., 0.],
       [6., 4., 3., 7.],
       [4., 9., 8., 9.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [123]:
np.concatenate([arr2, arr2b], axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4

In [125]:
arr2c = np.concatenate([arr2,np.array([[1,2,3,4]])])

In [126]:
arr2c

array([[0, 0, 0, 0],
       [6, 4, 3, 7],
       [4, 9, 8, 9],
       [1, 2, 3, 4]])

In [127]:
np.concatenate([arr2c, arr2b], axis=1) # axis=1 parametresi ile array'ler yan yana birleştirilir.

array([[0., 0., 0., 0., 1., 0., 0., 0.],
       [6., 4., 3., 7., 0., 1., 0., 0.],
       [4., 9., 8., 9., 0., 0., 1., 0.],
       [1., 2., 3., 4., 0., 0., 0., 1.]])

In [128]:
# vstack: vertical stack: dikey olarak birleştir
# hstock: horizontal stack: yatay olarak birleştir

In [130]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [4,5,6]])

In [131]:
np.concatenate([x,grid])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [132]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [4, 5, 6]])

In [133]:
grid

array([[9, 8, 7],
       [4, 5, 6]])

In [134]:
y = np.array([[99],[99]])

In [136]:
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 4,  5,  6, 99]])

In [138]:
x = np.arange(0,10)

In [139]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
np.split(x, [3, 5])

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9])]

In [147]:
np.split(x, [3, 5]) # Sınavda sorulabilir

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9])]

In [148]:
type(np.split(x, [3, 5]))

list

In [149]:
arr2c

array([[0, 0, 0, 0],
       [6, 4, 3, 7],
       [4, 9, 8, 9],
       [1, 2, 3, 4]])

In [150]:
np.vsplit(arr2c, [2])

[array([[0, 0, 0, 0],
        [6, 4, 3, 7]]),
 array([[4, 9, 8, 9],
        [1, 2, 3, 4]])]

In [151]:
np.hsplit(arr2c, [2])

[array([[0, 0],
        [6, 4],
        [4, 9],
        [1, 2]]),
 array([[0, 0],
        [3, 7],
        [8, 9],
        [3, 4]])]

In [152]:
# Bir array elemanlarının tersini hesaplayalım
buyuk_array = np.random.randint(1,100, size=1000000)

In [153]:
%timeit (1.0 / buyuk_array) # Çok daha hızlı !

14.5 ms ± 1.86 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [154]:
def tersini_hesapla(degerler):
    output = np.empty(len(degerler))
    for i in range(len(degerler)):
        output[i] = 1.0 / degerler[i]
    return output

In [155]:
tersini_hesapla(np.random.randint(1,100, size=5))

array([0.0125    , 0.01388889, 0.09090909, 0.03448276, 0.5       ])

In [156]:
%timeit tersini_hesapla(buyuk_array)

4.76 s ± 479 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
